spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myTest?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.springboottest.domain
  configuration:
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    # 该配置就是将带有下划线的表字段映射为驼峰格式的实体类属性
  global-config:
    db-config:
      logic-delete-field: activated #需要配置的逻辑删除数据库字段
      logic-delete-value: 0   #配置逻辑删除字段为1是删除
      logic-not-delete-value: 1  #配置逻辑删除字段为1是未删除



