spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myTest?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml
  type-aliases-package: com.example.springboottest.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

